package com.point.hr.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name="leaveRequests")
@Data // INFO: Generates getters and setters for all fields
@Builder
@AllArgsConstructor // INFO: Lombok generates a constructor with all fields
@NoArgsConstructor // INFO: Lombok generates an empty constructor (for JPA)
public class LeaveRequest {
    private static final String INFO_WHEN_REQUIRED = "is required";
    private static final String INFO_WHEN_END_DATE_TOO_EARLY = "End date cannot be earlier than start date";

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="lrId")
    //@NotNull(message = INFO_WHEN_REQUIRED // INFO: ID is generated by the database
    private Integer id;

    @Column(name = "lrPersonId", nullable = false)
    private Integer personId;

    @Column(name="lrLeaveTypeId", nullable = false)
    @NotNull(message = INFO_WHEN_REQUIRED)
    private Integer leaveTypeId;

    @Column(name="lrStartDate", nullable = false)
    @NotNull(message = INFO_WHEN_REQUIRED)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate startDate;

    @Column(name="lrEndDate", nullable = false)
    @NotNull(message = INFO_WHEN_REQUIRED)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate endDate;

    @Column(name="lrDurationDays")
    //@NotNull(message = INFO_WHEN_REQUIRED) // INFO: calculated in service
    private Integer durationDays;

    @Column(name="lrWhoAdded")
    private Integer whoAddedId;

    @Column(name="lrWhenAdded")
    @NotNull(message = INFO_WHEN_REQUIRED)
    private LocalDateTime whenAdded = LocalDateTime.now();

    /* Relationships */

    @ManyToOne
    @JoinColumn(name = "lrPersonId", referencedColumnName = "perId", insertable=false, updatable=false)
    //@JsonIgnore // INFO: Path in JSON output is not needed
    private Person person;

    @ManyToOne
    @JoinColumn(name = "lrWhoAdded", referencedColumnName = "perId", insertable=false, updatable=false)
    //@JsonIgnore // INFO: Path in JSON output is not needed
    private Person whoAdded;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "lrLeaveTypeId", insertable = false, updatable = false)
    private LeaveType leaveType;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "leaveRequest")
    private List<LeaveRequestStatus> leaveRequestStatuses;

    /* Validations */

    @AssertTrue(message = INFO_WHEN_END_DATE_TOO_EARLY)
    public boolean isEndDateAfterStartDate() {
        if (startDate == null || endDate == null) return true;

        return !endDate.isBefore(startDate);
    }

    /* LeaveRequest.toString() */

    @Override
    public String toString() {
        return "LeaveRequest{" +
                "id=" + id +
                ", personId=" + personId +
                ", leaveTypeId=" + leaveTypeId +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", durationDays=" + durationDays +
                ", whoAddedId=" + whoAddedId +
                ", whenAdded=" + whenAdded +
                '}';
    }
}
