package com.point.hr.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name="leaveRequests")
@Data
@Builder
@AllArgsConstructor // INFO: Lombok generates a constructor with all fields
@NoArgsConstructor // INFO: Lombok generates an empty constructor (for JPA)
public class LeaveRequest {

    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="lrId")
    //@NotNull(message = "is required") // INFO: ID is generated by the database
    private Integer id;

    @Getter
    @Setter
    @Column(name="lrLeaveTypeId")
    @NotNull(message = "is required")
    private Integer leaveTypeId;

    @Getter
    @Setter
    @Column(name="lrStartDate")
    @NotNull(message = "is required")
    private LocalDate startDate;

    @Getter
    @Setter
    @Column(name="lrEndDate")
    @NotNull(message = "is required")
    private LocalDate endDate;

    @Getter
    @Setter
    @Column(name="lrDurationDays")
    //@NotNull(message = "is required") // INFO: calculated in service
    private Integer durationDays;

    @Getter
    @Setter
    @Column(name="lrWhenAdded")
    @NotNull(message = "is required")
    private LocalDateTime whenAdded = LocalDateTime.now();

    /* Relationships */

    //@ManyToOne
    //@JoinColumn(name = "lrPersonId", referencedColumnName = "perId", insertable=false, updatable=false)
    //@JsonIgnore // INFO: Path in JSON output is not needed

    @Column(name="lrPersonId")
    private Integer personId;//Person person; // FIXME

    //@ManyToOne
    //@JoinColumn(name = "lrWhoAdded", referencedColumnName = "perId", insertable=false, updatable=false)
    //@JsonIgnore // INFO: Path in JSON output is not needed
    //private Person whoAdded; // FIXME

    @Column(name="lrWhoAdded")
    private Integer whoAdded;



    @Override
    public String toString() {
        return "LeaveRequest{" +
                "id=" + id +
                ", personId=" + personId + //person.getId() + // FIXME
                ", leaveTypeId=" + leaveTypeId +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", durationDays=" + durationDays +
                //", whoAdded=" + whoAdded.getId() + // FIXME
                ", whenAdded=" + whenAdded +
                '}';
    }
}
